import {
  extractConfigAndAdditionalInformation,
  parseTypicalConfig,
  parseWireguardConfig
} from './wireguardUtils';

describe('wireguardUtils', () => {
  describe('parseWireguardConfig', () => {
    test('should parse config', async () => {
      const result = parseWireguardConfig(mockedConfig);
      await expect(result).toEqual(parsedConfig);
    });
  });

  describe('parseTypicalConfig', () => {
    test('should original parse interface', async () => {
      const result = parseTypicalConfig(originalInterface);
      await expect(result).toEqual(parsedInterface);
    });

    test('should parse original peer', async () => {
      const result = parseTypicalConfig(originalPeer);
      await expect(result).toEqual(parsedPeer);
    });
  });

  describe('extractConfigAndAdditionalInformation', () => {
    test('should extract interface with additional data', async () => {
      const result = extractConfigAndAdditionalInformation(interfaceWithAdditionalData);
      await expect(result).toEqual(extractedInterfaceWithAdditionalData);
    });

    test('should extract peer with additional data', async () => {
      const result = extractConfigAndAdditionalInformation(peerWithAdditionalInformation);
      await expect(result).toEqual(extractedPeerWithAdditionalInformation);
    });

    test('should extract peer without additional data', async () => {
      const result = extractConfigAndAdditionalInformation(clearPeerWithAdditionalInformation);
      await expect(result).toEqual(extractedClearPeerWithAdditionalInformation);
    });
  });
});

const interfaceWithAdditionalData = `### Do not edit this file manually!
# customPropertyOne = tru-la-la
# customPropertyTwo = la-la-tru
[Interface]
PrivateKey = afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf
Address = 10.66.66.1/24
Address = fd42:42:42::1/64
ListenPort = 57418
PostUp = iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE`;

const extractedInterfaceWithAdditionalData = {
  title: `Do not edit this file manually!`,
  data: `customPropertyOne = tru-la-la
customPropertyTwo = la-la-tru`,
  type: `[Interface]`,
  config: `PrivateKey = afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf
Address = 10.66.66.1/24
Address = fd42:42:42::1/64
ListenPort = 57418
PostUp = iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE`
};

const peerWithAdditionalInformation = `### Client NL_PK_Mac
# customPropertyOne = tru-la-la-1
# customPropertyTwo = la-la-tru-2
[Peer]
PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128
`;

const extractedPeerWithAdditionalInformation = {
  title: `Client NL_PK_Mac`,
  data: `customPropertyOne = tru-la-la-1
customPropertyTwo = la-la-tru-2`,
  type: `[Peer]`,
  config: `PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128`
};

const clearPeerWithAdditionalInformation = `[Peer]
PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128
`;

const extractedClearPeerWithAdditionalInformation = {
  title: ``,
  data: ``,
  type: `[Peer]`,
  config: `PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128`
};

const originalInterface = `PrivateKey = afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf
Address = 10.66.66.1/24
Address = fd42:42:42::1/64
ListenPort = 57418
PostUp = iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE`;

const parsedInterface = {
  PrivateKey: 'afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf',
  Address: '10.66.66.1/24,fd42:42:42::1/64',
  ListenPort: '57418',
  PostUp:
    'iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT,iptables -A FORWARD -i wg0 -j ACCEPT,iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE,ip6tables -A FORWARD -i wg0 -j ACCEPT,ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE',
  PostDown:
    'iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT,iptables -D FORWARD -i wg0 -j ACCEPT,iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE,ip6tables -D FORWARD -i wg0 -j ACCEPT,ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE'
};

const originalPeer = `PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128`;

const parsedPeer = {
  PublicKey: 'dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf',
  PresharedKey: 'asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf',
  AllowedIPs: '10.66.66.2/32,fd42:42:42::2/128'
};

const mockedConfig = `### Do not edit this file manually!
# lastUpdate = 11.04.2022 22:33 (+0)
[Interface]
PrivateKey = afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf
Address = 10.66.66.1/24
Address = fd42:42:42::1/64
ListenPort = 57418
PostUp = iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

### Client NL_PK_Mac
# userName = tru-la-la-1
# firstName = la-la-tru-2
[Peer]
PublicKey = dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf
PresharedKey = asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128

### Client NL_PK_Phone
# userName = tru-la-la-3
# firstName = la-la-tru-4
[Peer]
PublicKey = dafkjs;fvmn,xcnvioqur0uwer[ujfas=
PresharedKey = asdfiop4iefjkdsafk;hjsiwue
AllowedIPs = 10.66.66.3/32,fd42:42:42::3/128

### Client NL_LV_Phone
# userName = tru-la-la-5
# firstName = la-la-tru-6
[Peer]
PublicKey = Yasdfkjsfk;auwioetrhjfds
PresharedKey = asdkfjfiu930wterioghjkfdls;ghjiuoerpwjkl
AllowedIPs = 10.66.66.4/32,fd42:42:42::4/128

### Client NL_KS_Win
[Peer]
PublicKey = dsfjhiueorpwtjkghiuopfjaklsgdhioutpwjerklghsdfi
PresharedKey = aklsjdfklasdasfhahshlflasjhfafs
AllowedIPs = 10.66.66.5/32,fd42:42:42::5/128
`;

const parsedConfig = {
  interface: {
    config: {
      Address: '10.66.66.1/24,fd42:42:42::1/64',
      ListenPort: '57418',
      PostDown:
        'iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT,iptables -D FORWARD -i wg0 -j ACCEPT,iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE,ip6tables -D FORWARD -i wg0 -j ACCEPT,ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE',
      PostUp:
        'iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT,iptables -A FORWARD -i wg0 -j ACCEPT,iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE,ip6tables -A FORWARD -i wg0 -j ACCEPT,ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE',
      PrivateKey: 'afsfsfasfakljfsda;ljfjal;sfjlajsfjasldf'
    },
    data: {
      lastUpdate: '11.04.2022 22:33 (+0)'
    },
    title: 'Do not edit this file manually!',
    type: '[Interface]'
  },
  peers: [
    {
      config: {
        AllowedIPs: '10.66.66.2/32,fd42:42:42::2/128',
        PresharedKey: 'asfjas;fjalksjdfioeuqrpoiuweioruiojdfsalkf',
        PublicKey: 'dsfjsfjaslkdjfoajsdf jasfjlasjdfl;j asldjf lajsdf'
      },
      data: {
        firstName: 'la-la-tru-2',
        userName: 'tru-la-la-1'
      },
      title: 'Client NL_PK_Mac',
      type: '[Peer]'
    },
    {
      config: {
        AllowedIPs: '10.66.66.3/32,fd42:42:42::3/128',
        PresharedKey: 'asdfiop4iefjkdsafk;hjsiwue',
        PublicKey: 'dafkjs;fvmn,xcnvioqur0uwer[ujfas='
      },
      data: {
        firstName: 'la-la-tru-4',
        userName: 'tru-la-la-3'
      },
      title: 'Client NL_PK_Phone',
      type: '[Peer]'
    },
    {
      config: {
        AllowedIPs: '10.66.66.4/32,fd42:42:42::4/128',
        PresharedKey: 'asdkfjfiu930wterioghjkfdls;ghjiuoerpwjkl',
        PublicKey: 'Yasdfkjsfk;auwioetrhjfds'
      },
      data: {
        firstName: 'la-la-tru-6',
        userName: 'tru-la-la-5'
      },
      title: 'Client NL_LV_Phone',
      type: '[Peer]'
    },
    {
      config: {
        AllowedIPs: '10.66.66.5/32,fd42:42:42::5/128',
        PresharedKey: 'aklsjdfklasdasfhahshlflasjhfafs',
        PublicKey: 'dsfjhiueorpwtjkghiuopfjaklsgdhioutpwjerklghsdfi'
      },
      data: {},
      title: 'Client NL_KS_Win',
      type: '[Peer]'
    }
  ]
};
