name: Build and Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Check bundle
        run: ls ${{ github.workspace }}/dist/node --all
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Create RUS envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BOT_CURRENT_NAME: "RUS"
          envkey_BOT_SETTINGS_RUS: ${{ secrets.BOT_SETTINGS_RUS }}
          file_name: .env
          fail_on_empty: false
      - name: Check .env file
        run: ls ${{ github.workspace }} --all
      - name: Deploy RUS env
        run: scp ${{ github.workspace }}/.env '${{ secrets.VPS_USER }}@${{ secrets.VPS_RUS_IP }}:/root/telegram-bot'
      - name: Deploy RUS app
        run: scp ${{ github.workspace }}/dist/node/telegram_bot.js '${{ secrets.VPS_USER }}@${{ secrets.VPS_RUS_IP }}:/root/telegram-bot'
      - name: Remove .env file
        run: rm ${{ github.workspace }}/.env
      - name: Check .env file
        run: ls ${{ github.workspace }} --all
      - name: Create NL envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BOT_CURRENT_NAME: "NL"
          envkey_BOT_SETTINGS_NL: ${{ secrets.BOT_SETTINGS_NL }}
          file_name: .env
          fail_on_empty: false
      - name: Check .env file
        run: ls ${{ github.workspace }} --all
      - name: Deploy NL env
        run: scp -P ${{ secrets.VPS_NL_PORT }} ${{ github.workspace }}/.env '${{ secrets.VPS_USER }}@${{ secrets.VPS_NL_IP }}:/root/telegram-bot'
      - name: Deploy NL app
        run: scp -P ${{ secrets.VPS_NL_PORT }} ${{ github.workspace }}/dist/node/telegram_bot.js '${{ secrets.VPS_USER }}@${{ secrets.VPS_NL_IP }}:/root/telegram-bot'
      - name: Create NL_OLD envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BOT_CURRENT_NAME: "NL_OLD"
          envkey_BOT_SETTINGS_NL_OLD: ${{ secrets.BOT_SETTINGS_NL_OLD }}
          file_name: .env
          fail_on_empty: false
      - name: Check .env file
        run: ls ${{ github.workspace }} --all
      - name: Deploy NL_OLD env
        run: scp -P ${{ secrets.VPS_NL_PORT }} ${{ github.workspace }}/.env '${{ secrets.VPS_USER }}@${{ secrets.VPS_NL_OLD_IP }}:/root/telegram-bot'
      - name: Deploy NL_OLD app
        run: scp -P ${{ secrets.VPS_NL_OLD_PORT }} ${{ github.workspace }}/dist/node/telegram_bot.js '${{ secrets.VPS_USER }}@${{ secrets.VPS_NL_OLD_IP }}:/root/telegram-bot'


